version: '3'

services:
  redis:
    container_name: redis
    image: redislabs/rejson
    sysctls:
      - net.core.somaxconn=1024
    restart: always

  bot:
    container_name: bot
    depends_on:
      - redis
    build: .
    restart: always
